---
- hosts: install-hosts
  become: yes
  roles:
    - kvm-hypervisor

- hosts: openshift
  remote_user: centos
  become: yes
  roles:
    - openshift-common

- hosts: node
  remote_user: centos
  become: yes
  roles:
    - openshift-node

- hosts: master
  remote_user: centos
  become: yes
  roles:
    - openshift-master
