---
# - hosts: install-hosts
#   become: yes
#   roles:
#     - kvm-hypervisor
#
# - hosts: openshift
#   remote_user: centos
#   become: yes
#   become_method: sudo
#   roles:
#     - openshift-common
#
# - hosts: openshift-nodes
#   remote_user: centos
#   become: yes
#   roles:
#     - openshift-node

- hosts: openshift-masters
  remote_user: centos
  become: yes
  roles:
    - openshift-master
