---
# tasks file for crio-replace

- name: install CRI-O repository
  yum:
    name: https://lsm5.fedorapeople.org/centos-release-container-1-3.el7.noarch.rpm
    state: present

- name: install CRI-O package
  yum:
    name: cri-o
    state: present

- name: enable OverlayFS storage
  lineinfile:
    name: /etc/crio/crio.conf
    regexp: '^storage_option'
    line: 'storage_option = [ "overlay2.override_kernel_check=1",'


- name: enable and start CRI-O service
  service:
    name: crio
    state: started
    enabled: yes

- name: enable CRI-O in OpenShift Node config
  blockinfile:
    name: /etc/origin/node/node-config.yaml
    insertafter: 'kubeletArguments:'
    block: |2
        image-service-endpoint:
        - "/var/run/crio.sock"
        container-runtime-endpoint:
        - "/var/run/crio.sock"
        container-runtime:
        - "remote"
        runtime-request-timeout:
        - "15m"
        enable-cri:
        - "true"

- name: restart Node service
  service:
    name: origin-node
    state: restarted

- name: stop and disable docker
  service:
    name: docker
    state: stopped
    enabled: no
    
# - name: start CRI-O
#   systemd:
#     name: crio
#     state: started
#     enabled: True
