---
# tasks file for openshift-master
- name: include distro-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: include distro-specific tasks
  include: "{{ ansible_distribution }}.yml"

- name: codify ssh public key filename
  set_fact:
    ssh_key_file_pub: "{{ ssh_key_file }}.pub"

- name: copy authorized key to remote user
  authorized_key:
    user: "{{ cluster_user }}"
    state: present
    key: "{{ lookup('file', ssh_key_file_pub) }}"

- name: copy private key to master
  copy:
    src: "{{ ssh_key_file }}"
    dest: "/home/{{ cluster_user }}/.ssh/id_rsa"
    owner: "{{ cluster_user }}"
    group: "{{ cluster_user }}"
    mode: 0400

- name: copy down autoinstaller repository
  git:
    repo: "{{ autoinstaller.repo }}"
    dest: "{{ autoinstaller.dest }}"

- name: set ownership of autoinstaller checkout
  file:
    name: "{{ autoinstaller.dest }}"
    state: directory
    owner: "{{ cluster_user }}"
    group: "{{ cluster_user }}"
    mode: 0755

- name: install inventory
  template:
    src: hosts.j2
    dest: "/home/{{ cluster_user }}/hosts"
    owner: "{{ cluster_user }}"
    group: "{{ cluster_user }}"

- name: install ansible config file for user
  template:
    src: ansible.cfg
    dest: "/home/{{ cluster_user }}/.ansible.cfg"
    owner: "{{ cluster_user }}"
    group: "{{ cluster_user }}"

- name: deploy openshift
  command: ansible-playbook -i /home/{{ cluster_user }}/hosts /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
  register: ocp_out
  when: deploy_openshift
  become: yes
  become_user: "{{ cluster_user }}"

- name: deploy output
  debug:
    msg: "{{ ocp_out.stdout }}"
  when: deploy_openshift
