---
# Chapter 2 exercise automation
# Be sure to reference the inventory file for your cluster.

- hosts: master
  remote_user: centos
  become: yes
  vars:
    server: https://{{ inventory_hostname }}:8443
    app_names:
    - app-cli
    - app-gui

  tasks:
  - name: log in as dev user
    command: oc login -u dev -p dev {{ server }}

  - name: Create image-uploader project
    command: oc new-project image-uploader --display-name="Image Uploader Project"

  - name: Deploy applications
    command: oc new-app --image-stream=php --code=https://github.com/OpenShiftInAction/image-uploader.git --name={{ item }}
    with_items: "{{ app_names }}"

  - name: Create routes for applications
    command: oc expose svc/{{ item }}
    with_items: "{{ app_names }}"
