---
# tasks file for openshift-master
- name: include distro-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: install dev packages for pip on master
  yum:
    name: "{{item}}"
    state: present
  with_items: "{{ dev_pkgs }}"

- name: install pip on master
  easy_install:
    name: pip
    state: latest

- name: install the proper version of ansible on master
  pip:
    name: ansible
    version: "{{ ansible_version }}"

- name: copy authorized key to remote user
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', ssh_key_pub) }}"

- name: copy private key to master
  copy:
    src: "{{ ssh_key }}"
    dest: /root/.ssh/id_rsa
    owner: root
    group: root
    mode: 0400

- name: copy down autoinstaller repository
  git:
    repo: "{{ autoinstaller.repo }}"
    dest: "{{ autoinstaller.dest }}"

- name: install config template
  template:
    src: installer.cfg.yml.j2
    dest: "{{ installer.dest }}"

- name: deploy openshift
  command: /bin/atomic-openshift-installer -u -c /root/installer.cfg.yml install --force
  register: ocp_out
  when: deploy_openshift

- name: deploy output
  debug:
    msg: "{{ deploy_openshigt.stdout }}"
