---
# tasks file for openshift-master
- name: include distro-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: install dev packages for pip on master
  yum:
    name: "{{item}}"
    state: present
  with_items: "{{ dev_pkgs }}"

- name: install pip on master
  easy_install:
    name: pip
    state: latest

- name: install the proper version of ansible on master
  pip:
    name: "{{ item }}"
  with_items:
    - pip==8.1.1
    - ansible==2.2.2.0

- name: copy authorized key to remote user
  authorized_key:
    user: "{{ kvm_host.remote_username }}"
    state: present
    key: "{{ lookup('file', instance.ssh_key.file_public ) }}"

- name: copy private key to master
  copy:
    src: "{{ instance.ssh_key.file_private }}"
    dest: /root/.ssh/id_rsa
    owner: root
    group: root
    mode: 0400

- name: copy down autoinstaller repository
  git:
    repo: "{{ autoinstaller.repo }}"
    dest: "{{ autoinstaller.dest }}"

- name: install config template
  template:
    src: installer.cfg.yml.j2
    dest: "{{ installer.dest }}"

- name: deploy openshift
  command: /bin/atomic-openshift-installer -u -c /root/installer.cfg.yml install --force
  register: ocp_out
  when: deployment.deploy_openshift

- name: deploy output
  debug:
    msg: "{{ ocp_out.stdout }}"
  when: deployment.deploy_openshift
