---
# tasks file for openshift-master
- name: include distro-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: include distro-specific tasks
  include: "{{ ansible_distribution }}.yml"

- name: get remote user from lookup table
  set_fact:
    cluster_user: "{{ remote_users[virt_type][openshift_type] }}"

- name: copy authorized key to remote user
  authorized_key:
    user: "{{ cluster_user }}"
    state: present
    key: "{{ lookup('file', instance.ssh_key.file_public ) }}"

- name: copy private key to master
  copy:
    src: "{{ instance.ssh_key.file_private }}"
    dest: /root/.ssh/id_rsa
    owner: root
    group: root
    mode: 0400

- name: copy down autoinstaller repository
  git:
    repo: "{{ autoinstaller.repo }}"
    dest: "{{ autoinstaller.dest }}"

- name: install inventory
  template:
    src: hosts.j2
    dest: "{{ installer.dest }}"

- name: deploy openshift
  command: ansible-playbook -i {{ installer.dest }} /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
  register: ocp_out
  when: deployment.deploy_openshift

- name: deploy output
  debug:
    msg: "{{ ocp_out.stdout }}"
  when: deployment.deploy_openshift
