- name: create VPC for OpenShift cluster
  ec2_vpc_net:
    aws_secret_key: "{{ aws_secret_access_key }}"
    aws_access_key: "{{ aws_secret_key_id }}"
    name: OpenShift
    cidr_block: "{{ networks.private.openshift_int.subnet_cidr }}"
    region: "{{ region }}"
    tags:
      project: openshift
  register: vpc_info

- name: set VPC ID fact
  set_fact:
    vpc_id: "{{ vpc_info.vpc.id }}"
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['all'] }}"

- name: Create gateway uplink for VPC
  ec2_vpc_igw:
    aws_secret_key: "{{ aws_secret_access_key }}"
    aws_access_key: "{{ aws_secret_key_id }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    state: present
  register: vpc_igw

- name: create VPC subnet
  ec2_vpc_subnet:
    aws_secret_key: "{{ aws_secret_access_key }}"
    aws_access_key: "{{ aws_secret_key_id }}"
    state: present
    cidr: "{{ networks.private.openshift_int.subnet_cidr }}"
    region: "{{ region }}"
    resource_tags:
      Name: OpenShift Subnet
    vpc_id: "{{ vpc_id }}"
  register: ocp_subnet

- name: set VPC Subnet ID fact
  set_fact:
    subnet_id: "{{ ocp_subnet.subnet.id }}"

- name: Lookup route tables
  ec2_vpc_route_table_facts:
    aws_secret_key: "{{ aws_secret_access_key }}"
    aws_access_key: "{{ aws_secret_key_id }}"
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_id }}"
  register: vpc_route_tables

- name: Set up public subnet route 
  ec2_vpc_route_table:
    aws_secret_key: "{{ aws_secret_access_key }}"
    aws_access_key: "{{ aws_secret_key_id }}"
    state: present
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    lookup: id
    purge_subnets: false
    route_table_id: "{{ vpc_route_tables.route_tables[0].id }}"
    subnets:
      - "{{ ocp_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ vpc_igw.gateway_id }}"
