---
# Chapter 6 automation playbook
# Be sure to reference the inventory file for your cluster.

- hosts: openshift-masters
  remote_user: centos
  become: yes
  vars:
    master_config_file: /etc/origin/master/master-config.yaml
    htpasswd_file: /etc/origin/master/openshift.htpasswd
    openshift_users:
    - developer
    - project-admin
    - admin

  tasks:
  - name: create users in htpasswd database
    htpasswd:
      path: "{{ htpasswd_file }}"
      name: "{{ item }}"
      password: "{{ item }}"
      owner: root
      group: root
      mode: 0640
    with_items: "{{ openshift_users }}"

  - name: remove allow_all provider
    blockinfile:
      dest: "{{ master_config_file }}"
      state: present
      marker: # To be removed 
      block: |2
        - challenge: true
          login: true
          mappingMethod: claim
          name: allow_all
          provider:
            apiVersion: v1
            kind: AllowAllPasswordIdentityProvider

  - name: add htpasswd provider
    blockinfile:
      dest: "{{ master_config_file }}"
      insertafter: "identityProviders:"
      block: |2
        - name: my_htpasswd_provider
          challenge: true
          login: true
          mappingMethod: claim
          provider:
            apiVersion: v1
            kind: HTPasswdPasswordIdentityProvider
            file: {{ htpasswd_file }}
