---
# Chapter 2 exercise automation
# Be sure to reference the inventory file for your cluster.

- hosts: openshift-masters
  remote_user: centos
  become: yes
  vars:
    project: image-uploader
    project_desc: Image Uploader Project
    app_names:
    - app-cli
    - app-gui

  tasks:
  - name: log in as dev user
    command: oc login -u dev -p dev https://ocp1.192.168.122.100.nip.io:8443

  - name: Create image-uploader project
    command: oc new-project {{ project }} --display-name={{ project_desc }}

  - name: Deploy applications
    command: oc new-app --image-stream=php --code=https://github.com/OpenShiftInAction/image-uploader.git --name={{ item }}
    with_items: "{{ app_names }}"

  - name: Create routes for applications
    command: oc expose svc/{{ item }}
    with_items: "{{ app_names }}"
