---
# Appendix B automation playbook
# Be sure to reference the inventory file for your cluster.

- hosts: openshift-masters
  remote_user: centos
  become: yes
  vars:
    install_directory: /root/autoinstaller
    nfs_server_host: 192.168.122.100
    nfs_export_dirs:
    - pv01
    - pv02
    - pv03
    - pv04
    - pv05
    app_names:
    - app-cli
    - app-gui

  tasks:
  - name: create PV templates
    template:
      src: pv.yaml.j2
      dest: /root/{{ item }}.yaml
    with_items: "{{ nfs_export_dirs }}"

  - name: log in as system:admin
    command: oc login -u system:admin

  - name: create PVs
    command: oc create -f /root/{{ item }}.yaml
    with_items: "{{ nfs_export_dirs }}"

  - name: log in as dev user
    command: oc login -u dev -p dev https://192.168.122.100:8443

  - name: create PVC templates
    template:
      src: pvc.yaml.j2
      dest: /root/pvc-{{ item }}.yaml
    with_items: "{{ app_names }}"

  - name: create PVCs
    command: oc create -f /root/pvc-{{ item }}.yaml
    with_items: "{{ app_names }}"

  - name: add volumes to applications
    command: oc volume dc/{{ item }} --add --type=persistentVolumeClaim --claim-name={{ item }} --mount-path=/opt/app-root/src/uploads
    with_items: "{{ app_names }}"
