---
# Chapter 2 exercise automation
# Be sure to reference the inventory file for your cluster.

- hosts: openshift-masters
  remote_user: centos
  become: yes

  tasks:
  - name: Create image-uploader project
    command: oc new-project image-uploader --display-name='Image Uploader Project'

  - name: Deploy app-cli
    command: oc new-app --image-stream=php --code=https://github.com/OpenShiftInAction/image-uploader.git --name=app-cli

  - name: Create route for app-cli
    command: oc expose svc/app-cli

  - name: Deploy app-gui
    command: oc new-app --image-stream=php --code=https://github.com/OpenShiftInAction/image-uploader.git --name=app-gui

  - name: Create route for app-gui
    command: oc expose svc/app-gui
