---
# Appendix B automation playbook
# Be sure to reference the inventory file for your cluster.

- hosts: openshift-masters
  remote_user: centos
  become: yes
  vars:
    install_directory: /root/autoinstaller
    nfs_server_host: 192.168.122.100
    nfs_export_dirs:
    - pv01
    - pv02
    - pv03
    - pv04
    - pv05
    app_names:
    - app-cli
    - app-gui

  tasks:
  - name: create PV templates
    template:
      src: pv.yaml.j2
      dest: /root/{{ item }}.yaml
    with_items: "{{ nfs_export_dirs }}"

  - name: create PVs
    command: oc create -f {{ item }}.yaml
    with_items: "{{ nfs_export_dirs }}"

  - name: create PVC templates
    template:
      src: pvc.yaml.j2
      dest: pvc-{{ item }}.yaml
    with_items: "{{ app_names }}"

  - name: create PVCs
    command: oc create -f pvc-{{ item }}.yaml
    with_items: "{{ app_names }}"

  - name: add volumes to applications
    command: oc volume add dc/{{ item }} --add --type=persistentVolumeClaim --claim-name={{ item }} --mount-path=/opt/app-root/src/uploads
