---
# tasks file for openstack-hypervisor
# This creates all of the resources needed to build out an entire OCP instance on openstack-hypervisor
# including the networking, ssh-keys, etc.

- name: ensure module dependencies are installed
  become: yes
  pip:
    name: "{{ item }}"
    state: present
  with_items:
  - shade
  - futures
  - jmespath

- name: include security-related tasks
  include: os_security.yml
  when: set_up_security

- name: include networking tasks
  include: os_networking.yml
  when: set_up_network

- name: create openshift-specific flavor
  os_nova_flavor:
    auth:
      auth_url: "{{ auth_creds.url }}"
      username: "{{ auth_creds.admin.username }}"
      password: "{{ auth_creds.admin.password }}"
      project_name: "{{ auth_creds.admin.project }}"
    state: present
    name: "{{ flavor.name }}"
    ram: "{{ flavor.ram }}"
    vcpus: "{{ flavor.vcpus }}"
    disk: "{{ flavor.disk }}"
    ephemeral: "{{ flavor.ephemeral }}"

- name: create openshift nodes
  os_server:
    auth:
      auth_url: "{{ auth_creds.url }}"
      username: "{{ auth_creds.username }}"
      password: "{{ auth_creds.password }}"
      project_name: "{{ auth_creds.project }}"
    state: present
    flavor: "{{ flavor.name }}"
    image: "{{ instance.image_id }}"
    key_name: "{{ ssh_key.name }}"
    network: "{{ private_network.name }}"
    name: "{{ hostvars[item]['inventory_hostname'] }}"
    auto_ip: yes
    security_groups: "{{ security_group.name }}"
    meta: "role={{ hostvars[item]['role'] }}"
  with_items: "{{ groups['openshift'] }}"

- name: gather openstack facts
  os_server_facts:
    auth:
      auth_url: "{{ auth_creds.url }}"
      username: "{{ auth_creds.username }}"
      password: "{{ auth_creds.password }}"
      project_name: "{{ auth_creds.project }}"
    server: ocp*

- name: debug openstack facts
  debug:
    var: openstack_servers
