---
# tasks file for openstack-hypervisor
# This creates all of the resources needed to build out an entire OCP instance on openstack-hypervisor
# including the networking, ssh-keys, etc.
- name: ensure module dependencies are installed
  become: yes
  pip:
    name: "{{ item }}"
    state: present
  with_items:
  - shade
  - futures
  - jmespath

- name: ensure keypair is created in OpenStack
  os_keypair:
    auth:
      auth_url: {{ auth_creds.url }}
      username: {{ auth_creds.username }}
      password: {{ auth_creds.password }}
      project_name: {{ auth_creds.project }}
    name: "{{ ssh_key_name }}"
    public_key_file: "{{ ssh_key_file }}"
