---
# openstack networking setup

- name: create private network
  os_network:
    name: "{{ private_network.name }}"
    auth:
      auth_url: "{{ auth_creds.url }}"
      username: "{{ auth_creds.username }}"
      password: "{{ auth_creds.password }}"
      project_name: "{{ auth_creds.project }}"
    project: "{{ auth_creds.project }}"
    state: present
    wait: yes

- name: create subnet on private network
  os_subnet:
    auth:
      auth_url: "{{ auth_creds.url }}"
      username: "{{ auth_creds.username }}"
      password: "{{ auth_creds.password }}"
      project_name: "{{ auth_creds.project }}"
    name: "{{ private_network.subnet_name }}"
    network_name: "{{ private_network.name }}"
    state: present
    cidr: "{{ private_network.subnet_cidr }}"
    dns_nameservers:
      - "{{ private_network.subnet_dns[0] }}"
      - "{{ private_network.subnet_dns[1] }}"

- name: create router for project
  os_router:
    auth:
      auth_url: "{{ auth_creds.url }}"
      username: "{{ auth_creds.username }}"
      password: "{{ auth_creds.password }}"
      project_name: "{{ auth_creds.project }}"
    state: present
    name: "{{ external_network.router_name }}"
    network: "{{ external_network.name }}"
    interfaces:
      - "{{ private_network.subnet_name }}"
