---
# openstack networking setup

- name: create private networks
  os_network:
    auth:
      auth_url: "{{ auth_creds.url }}"
      username: "{{ auth_creds.username }}"
      password: "{{ auth_creds.password }}"
      project_name: "{{ auth_creds.project }}"
    project: "{{ auth_creds.project }}"
    state: present
    name: "{{ item.key }}"
    wait: yes
  with_dict: "{{ networks.private }}"


- name: create subnets on private networks
  os_subnet:
    auth:
      auth_url: "{{ auth_creds.url }}"
      username: "{{ auth_creds.username }}"
      password: "{{ auth_creds.password }}"
      project_name: "{{ auth_creds.project }}"
    name: "{{ item.key }}"
    network_name: "{{ item.value.subnet_name }}"
    state: present
    cidr: "{{ item.value.subnet_cidr }}"
    dns_nameservers:
      - "{{ item.value.subnet_dns[0] }}"
      - "{{ item.value.subnet_dns[1] }}"
  with_dict: "{{ networks.private }}"

- name: create router for project
  os_router:
    auth:
      auth_url: "{{ auth_creds.url }}"
      username: "{{ auth_creds.username }}"
      password: "{{ auth_creds.password }}"
      project_name: "{{ auth_creds.project }}"
    state: present
    name: "{{ networks.external.public.router_name }}"
    network: "{{ networks.external.public.name }}"
    interfaces:
      - "{{ item.value.subnet_name }}"
  with_dict: "{{ networks.private }}"
