---
- name: include distribution-specific common tasks
  include: "{{ ansible_distribution }}.yaml"

- name: set SELinux booleans to allow for persistent storage
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items: "{{ selinux_bools }}"

- name: update systems
  yum:
    name: '*'
    state: latest

- name: restart server
  shell: ( sleep 3 && /sbin/reboot & )

- name: wait for server to come back
  local_action: wait_for host={{ ansible_ssh_host }} state=started delay=30 timeout=90 port=22
  become: false
