rhn_repos:
  - rhel-7-server-rpms
  - rhel-7-server-ose-{{ openshift_version }}-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-fast-datapath-rpms

base_pkgs:
  - wget
  - git
  - net-tools
  - bind-utils
  - iptables-services
  - bridge-utils
  - bash-completion
  - kexec-tools
  - sos
  - psacct
  - vim-enhanced
  - atomic-openshift-utils
  - docker

rhn_user: "{{ lookup('env','RHN_USERNAME') }}"
rhn_pass: "{{ lookup('env','RHN_PASSWORD') }}"
rhn_pool_id: "{{ lookup('env','RHN_POOL_ID') }}"
