---
# vars file for openstack-hypervisor
ansible_deps:
  - shade
  - futures
  - jmespath

auth_creds:
  url: "{{ auth_url }}"
  username: "{{ lookup('env', 'OS_USERNAME') }}"
  password: "{{ lookup('env', 'OS_PASSWORD') }}"
  project: "{{ project }}"

# Create custom security group
setup_security: true
# Create network / subnet
setup_network: true

security_group:
  name: openshift
  desc: OpenShift security group
  rules:
    allow_all_internal:
      protocol: tcp
      port_range_min: -1
      port_range_max: -1
      remote_ip_prefix: "{{ networks.private.openshift_int.subnet_cidr }}"
    allow_8443_public:
      protocol: tcp
      port_range_min: 8443
      port_range_max: 8443
      remote_ip_prefix: "{{ networks.external.public.subnet_cidr }}"
    allow_22_public:
      protocol: tcp
      port_range_min: 22
      port_range_max: 22
      remote_ip_prefix: "{{ networks.external.public.subnet_cidr }}"
