---
# tasks file for openshift-common
# - name: set hostname
#   hostname:
#     name: "{{ hostname }}"

- name: include distribution-specific common tasks
  include: "{{ ansible_distribution }}.yaml"

- name: set SELinux booleans to allow for persistent storage
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items:
    - virt_use_nfs
    - virt_sandbox_use_nfs

- name: reboot each system
  shell: sleep 2 && systemctl reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=90 port=22
  become: false
