---
# tasks file for openshift-common
- name: set hostname
  hostname:
    name: "{{ hostname }}"

- name: install needed repositories
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - centos-release-openshift-origin

- name: install needed packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - origin
    - origin-clients
    - vim-enhanced
    - atomic-openshift-utils
    - NetworkManager

- name: enable and start NetworkManager
  service:
    name: NetworkManager
    state: started
    enabled: yes

- name: reboot each system
  shell: sleep 2 && systemctl reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300 port=22
  become: false
