- name: Register system
  redhat_subscription:
    state: present
    username: {{ rhn_user }}
    password: {{ rhn_pass }}
    pool_ids: {{ rhn_pool_id }}

- name: disable all repos
  command: subscription-manager repos --disable="*"

- name: enable needed repositories
  command: subscription-manager repos --enable={{ item }}
  with_items: "{{ rhn_repos }}"

- name: install base packages
  yum:
    state: present
    name: "{{ item }}"
  with_items: "{{ base_pkgs }}"

- name: update system
  yum:
    state: latest
    name: *
