centos_image: CentOS-7-x86_64-GenericCloud.qcow2
centos_image_loc: https://cloud.centos.org/centos/7/images/{{ centos_image }}
centos_image_dir: /tmp
centos_image_local: "{{ centos_image_dir}}/{{ centos_image }}"
